[book]
title = "Typst Extra Docs"
authors = []
description = "An unofficial collection of extra official documentations for Typst."
language = "en"

[output.html.search.chapter]
# Disables search indexing for licenses
"license" = { enable = false }

[output.html.playground]
# hayagriva/index.md contains rust codes, but the Rust Playground does not support the hayagriva crate
runnable = false

[preprocessor.typst-highlight]
# Install it by running
#   cargo install --git https://github.com/sitandr/mdbook-typst-highlight --branch main
# It's d7c197c6, the unreleased version.

# Inline highlighting must be disabled due to technical limitations.
# This preprocessor highlights inline codes by converting them to HTML fragments in markdown.
# However, special characters (e.g., `_*|`) in them are not properly escaped, resulting in poor rendering.
disable_inline = true

[preprocessor.typst-extra-docs]
command = "cargo run --release --manifest-path ./typst-extra-docs/Cargo.toml"

[preprocessor.typst-extra-docs.download]
# Format: `git log -1 --format='%h %ad' --date=iso-strict`
# `%ad` can also be obtained from GitHub API: `gh api /repos/typst/REPO/commits/COMMIT --jq .commit.author.date`
typst = "909c0028d 2026-01-26T16:34:01-05:00"
codex = "7f60dcc 2026-01-26T08:02:25Z"
hayagriva = "a137441 2025-12-27T22:30:59Z"
packages = "145b87e 2026-01-26T22:32:26Z"
