[book]
title = "Typst Extra Docs"
authors = []
description = "An unofficial collection of extra official documentations for Typst."
language = "en"

[output.html.search.chapter]
# Disables search indexing for licenses
"license" = { enable = false }

[preprocessor.typst-extra-docs]
command = "cargo run --release --manifest-path ./typst-extra-docs/Cargo.toml"
