[book]
title = "Typst Extra Docs"
authors = []
description = "An unofficial collection of extra official documentations for Typst."
language = "en"

[output.html.search.chapter]
# Disables search indexing for licenses
"license" = { enable = false }

[preprocessor.typst-highlight]
# https://github.com/sicikh/mdbook-typst-highlight/tree/06056f4759bc7191f0cdec30473b2d2299d6038d
# https://github.com/sitandr/mdbook-typst-highlight/pull/3
# That's a fork of https://github.com/sitandr/mdbook-typst-highlight
command = "cargo run --release --manifest-path ../mdbook-typst-highlight/Cargo.toml"
# Inline highlighting must be disabled due to technical limitations.
# This preprocessor highlights inline codes by converting them to HTML fragments in markdown.
# However, special characters (e.g., `_*|`) in them are not properly escaped, resulting in poor rendering.
disable_inline = true

[preprocessor.typst-extra-docs]
command = "cargo run --release --manifest-path ./typst-extra-docs/Cargo.toml"

[preprocessor.typst-extra-docs.download]
# Format: `git log -1 --format='%h %ad' --date=iso-strict`
# `%ad` can also be obtained from GitHub API: `gh api /repos/typst/REPO/commits/COMMIT --jq .commit.author.date`
typst = "701c7f9b2 2026-01-15T23:43:26+01:00"
codex = "cd6d10d73 2025-12-19T20:21:19Z"
hayagriva = "a137441 2025-12-27T22:30:59Z"
packages = "09e558d 2026-01-16T17:13:40Z"
