[project]
name = "typst-extra-docs"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
]

[tool.ruff]
line-length = 120 # For long URLs

[tool.ruff.lint]
extend-select = ["U", "TYP", "F", "I"]
